In [1]:
import pandas as pd

In [2]:
dff={
    "Name":["Anukul",'Shyam','Hari','Sita'],
    'Age':[20,30,34,23],
    'Salary':[20000,25000,30000,32000]
}

In [3]:
df=pd.DataFrame(dff)
df

     Name  Age  Salary
0  Anukul   20   20000
1   Shyam   30   25000
2    Hari   34   30000
3    Sita   23   32000

In [5]:
df['doj']=['15-1-2024','16-1-2024','17-3-2024','18-3-2024']

In [6]:
df['doj']=pd.to_datetime(df['doj'],format='%d-%m-%Y')
df

     Name  Age  Salary        doj
0  Anukul   20   20000 2024-01-15
1   Shyam   30   25000 2024-01-16
2    Hari   34   30000 2024-03-17
3    Sita   23   32000 2024-03-18

In [12]:
df['month']=df['doj'].dt.month
df

     Name  Age  Salary        doj  month
0  Anukul   20   20000 2024-01-15      1
1   Shyam   30   25000 2024-01-16      1
2    Hari   34   30000 2024-03-17      3
3    Sita   23   32000 2024-03-18      3

In [13]:
#Aggreation and groupby

In [14]:
df['month'].value_counts()# it gives frequency of values

month
1    2
3    2
Name: count, dtype: int64

In [15]:
df[df['month']==1].value_counts()

Name    Age  Salary  doj         month
Anukul  20   20000   2024-01-15  1        1
Shyam   30   25000   2024-01-16  1        1
Name: count, dtype: int64

In [16]:
df.groupby('month')['Salary'].sum()#Aggregration based on group by
#it gives sum of same month

month
1    45000
3    62000
Name: Salary, dtype: int64

In [17]:
df.groupby('month')['Salary'].mean()

month
1    22500.0
3    31000.0
Name: Salary, dtype: float64