In [15]:
import pandas as pd

In [16]:
dff={
    "Name":["ram",'hari','shyam'],
    'salary':[60000,70000,80000],
    'age':[20,21,22]
    
}

In [17]:
df=pd.DataFrame(dff)
df

    Name  salary  age
0    ram   60000   20
1   hari   70000   21
2  shyam   80000   22

In [18]:
df['doj']=['2026-8-9' , '2026-8-7', '2026-8-10']
df

    Name  salary  age        doj
0    ram   60000   20   2026-8-9
1   hari   70000   21   2026-8-7
2  shyam   80000   22  2026-8-10

In [19]:
df['doj']=pd.to_datetime(df['doj'])
df['doj'].dtype

dtype('<M8[ns]')

In [20]:
df['doj2']=['15-4-2025','16-6-2025','17-5-2025']
df['doj2'].dtype

dtype('O')

In [21]:
df['doj2']=pd.to_datetime(df['doj2'],format='%d-%m-%Y')#in this we have to give format of day,month,year
df

    Name  salary  age        doj       doj2
0    ram   60000   20 2026-08-09 2025-04-15
1   hari   70000   21 2026-08-07 2025-06-16
2  shyam   80000   22 2026-08-10 2025-05-17

In [22]:
df=df.drop('doj',axis=1)
df

    Name  salary  age       doj2
0    ram   60000   20 2025-04-15
1   hari   70000   21 2025-06-16
2  shyam   80000   22 2025-05-17

In [23]:
df['doj2'].dt.year#it gives year

0    2025
1    2025
2    2025
Name: doj2, dtype: int32

In [24]:
df['doj2'].dt.month

0    4
1    6
2    5
Name: doj2, dtype: int32

In [27]:
df['doj2'].dt.day

0    15
1    16
2    17
Name: doj2, dtype: int32

In [29]:
df['doj2'].dt.day_name()

0     Tuesday
1      Monday
2    Saturday
Name: doj2, dtype: object

In [31]:
#if i want to add 30 days in each row of doj2
df['doj2']+pd.Timedelta(days=30)

0   2025-05-15
1   2025-07-16
2   2025-06-16
Name: doj2, dtype: datetime64[ns]