In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame({
    'id':[1,2,3],
    'salary':[1000,2000,3000]
})
df

   id  salary
0   1    1000
1   2    2000
2   3    3000

In [3]:
df1=pd.DataFrame({
    'id':[3,4,5],
    'score':[10,11,12]
})
df1

   id  score
0   3     10
1   4     11
2   5     12

In [4]:
# Concatenate

In [6]:
pd.concat([df,df1],axis=0,ignore_index=True)#it concat vertically , top on top,row level

   id  salary  score
0   1  1000.0    NaN
1   2  2000.0    NaN
2   3  3000.0    NaN
3   3     NaN   10.0
4   4     NaN   11.0
5   5     NaN   12.0

In [8]:
pd.concat([df,df1],axis=1)#horizontal/column level/ side on side

   id  salary  id  score
0   1    1000   3     10
1   2    2000   4     11
2   3    3000   5     12

In [9]:
#merge - joins

In [10]:
pd.merge(df,df1,how='inner',on='id')

   id  salary  score
0   3    3000     10

In [11]:
pd.merge(df,df1,how='outer',on='id')

   id  salary  score
0   1  1000.0    NaN
1   2  2000.0    NaN
2   3  3000.0   10.0
3   4     NaN   11.0
4   5     NaN   12.0

In [12]:
pd.merge(df,df1,how='inner',left_on='id',right_on='id')

   id  salary  score
0   3    3000     10