In [1]:
#Create dataframe
#Data frame is a two‑dimensional, tabular data structure with labeled rows and columns

In [2]:
import pandas as pd

In [7]:
df=pd.DataFrame([10,20,30],  columns=['number'])
print(df)

   number
0      10
1      20
2      30

In [8]:
data={
    'name':['anukul','ram','hari'],
    'age':[12,13,14],
    'salary':[2000,3000,4000]
}

In [9]:
df=pd.DataFrame(data)
print(df)

     name  age  salary
0  anukul   12    2000
1     ram   13    3000
2    hari   14    4000

In [10]:
#Basic understanding of dataframe

In [11]:
df.head(2)#gives top 2 rows

     name  age  salary
0  anukul   12    2000
1     ram   13    3000

In [12]:
df.tail(2)#gives last rows

   name  age  salary
1   ram   13    3000
2  hari   14    4000

In [14]:
df.isna().sum()#it check null and sum of all null if they exists

name      0
age       0
salary    0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.shape#it gives number of row and column

(3, 3)

In [20]:
df.columns

Index(['name', 'age', 'salary'], dtype='object')

In [23]:
df.rename(columns={'salary':'monthly_salary'},inplace=True)#inplace =true means i want to change in this df variable

In [26]:
df

     name  age  monthly_salary
0  anukul   12            2000
1     ram   13            3000
2    hari   14            4000