In [44]:
#Dataframe operation

In [45]:
import pandas as pd

In [46]:
df=pd.read_csv('students.csv')
df.head()

    Name  Math  Science  English  Computer  Social
0    Ram    44       33       65        61      58
1   Sita    47       43       99        41      84
2   Hari    34       33       41        57      59
3   Gita    94       33       55        99      83
4  Shyam    58       87       65        30      50

In [47]:
#add new columns with zero value
df['label']=0

In [48]:
df.head()

    Name  Math  Science  English  Computer  Social  label
0    Ram    44       33       65        61      58      0
1   Sita    47       43       99        41      84      0
2   Hari    34       33       41        57      59      0
3   Gita    94       33       55        99      83      0
4  Shyam    58       87       65        30      50      0

In [49]:
#update  value
df.loc[0,'Name']='Anukul'
df.head()

     Name  Math  Science  English  Computer  Social  label
0  Anukul    44       33       65        61      58      0
1    Sita    47       43       99        41      84      0
2    Hari    34       33       41        57      59      0
3    Gita    94       33       55        99      83      0
4   Shyam    58       87       65        30      50      0

In [50]:
#drop row ,if  i want to drop shyam row
df=df.drop(df[df.Name=='Shyam'].index)
df.head()

     Name  Math  Science  English  Computer  Social  label
0  Anukul    44       33       65        61      58      0
1    Sita    47       43       99        41      84      0
2    Hari    34       33       41        57      59      0
3    Gita    94       33       55        99      83      0
5    Mina    84       73       65        49      57      0

In [51]:
df[df.Name=='Shyam']

Empty DataFrame
Columns: [Name, Math, Science, English, Computer, Social, label]
Index: []

In [52]:
df=df.drop('label',axis=1)#columns drop ,axis=1 means by default axis =0 it's for row,  for columns axis =1
df.head()

     Name  Math  Science  English  Computer  Social
0  Anukul    44       33       65        61      58
1    Sita    47       43       99        41      84
2    Hari    34       33       41        57      59
3    Gita    94       33       55        99      83
5    Mina    84       73       65        49      57

In [53]:
#sort value
df.sort_values('Math')#by defualt it is in ascending order

       Name  Math  Science  English  Computer  Social
28    Nisha    32       44       76        69      60
2      Hari    34       33       41        57      59
29  Krishna    37       60       40        40      92
36    Rohan    37       59       38        34      72
30    Rabin    38       98       46        46      90
16    Kamal    38       57       70        57      93
37    Priya    39       95       60        65      92
20    Bibek    41       36       44        49      50
0    Anukul    44       33       65        61      58
1      Sita    47       43       99        41      84
13    Dipak    51       98       61        50      89
32   Sushil    57       99       55        69      81
38    Manoj    57       99       46        90      61
15   Roshan    59       34       70        81      64
10    Suman    59       67       40        59      42
18   Aakash    61       98       63        84      81
34  Sandesh    61       58       38        73      32
9      Rita    67       76       54        38      35
6     Kiran    73       43       41        78      42
7     Anita    75       74       63        35      88
19  Prakash    76       58       47        95      93
12   Sarita    77       75       56        64      39
33    Rekha    77       86       96        87      45
11    Nabin    78       65       88        76      50
14     Puja    78       64       58        71      37
17   Sunita    80       88       48        63      47
5      Mina    84       73       65        49      57
21  Manisha    84       38       79        78      89
24   Ashish    85       50       88        30      63
39    Kusum    90       82       54        42      42
25   Ramesh    94       52       94        43      68
3      Gita    94       33       55        99      83
26    Sneha    94       55       49        77      50
22    Sagar    97       62      100        31      44
23   Sabina    98       64       73        44      67
8    Bikash    98       45       78        40     100
27    Arjun    99       97       30        71      92
31   Binita   100       51       63        97      84
35   Asmita   100       59       58        30      39

In [55]:
#descending order
df.sort_values('Math',ascending=False)

       Name  Math  Science  English  Computer  Social
35   Asmita   100       59       58        30      39
31   Binita   100       51       63        97      84
27    Arjun    99       97       30        71      92
8    Bikash    98       45       78        40     100
23   Sabina    98       64       73        44      67
22    Sagar    97       62      100        31      44
3      Gita    94       33       55        99      83
26    Sneha    94       55       49        77      50
25   Ramesh    94       52       94        43      68
39    Kusum    90       82       54        42      42
24   Ashish    85       50       88        30      63
21  Manisha    84       38       79        78      89
5      Mina    84       73       65        49      57
17   Sunita    80       88       48        63      47
14     Puja    78       64       58        71      37
11    Nabin    78       65       88        76      50
33    Rekha    77       86       96        87      45
12   Sarita    77       75       56        64      39
19  Prakash    76       58       47        95      93
7     Anita    75       74       63        35      88
6     Kiran    73       43       41        78      42
9      Rita    67       76       54        38      35
34  Sandesh    61       58       38        73      32
18   Aakash    61       98       63        84      81
10    Suman    59       67       40        59      42
15   Roshan    59       34       70        81      64
38    Manoj    57       99       46        90      61
32   Sushil    57       99       55        69      81
13    Dipak    51       98       61        50      89
1      Sita    47       43       99        41      84
0    Anukul    44       33       65        61      58
20    Bibek    41       36       44        49      50
37    Priya    39       95       60        65      92
30    Rabin    38       98       46        46      90
16    Kamal    38       57       70        57      93
36    Rohan    37       59       38        34      72
29  Krishna    37       60       40        40      92
2      Hari    34       33       41        57      59
28    Nisha    32       44       76        69      60