In [1]:
#Filtering data frame

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('students.csv')

In [4]:
print(df.head())

    Name  Math  Science  English  Computer  Social
0    Ram    44       33       65        61      58
1   Sita    47       43       99        41      84
2   Hari    34       33       41        57      59
3   Gita    94       33       55        99      83
4  Shyam    58       87       65        30      50

In [20]:
(df['Computer']>80)#in this it give all value false and true but i want only true value in this case we do

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18     True
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31     True
32    False
33     True
34    False
35    False
36    False
37    False
38     True
39    False
Name: Computer, dtype: bool

In [6]:
df[df['Computer']>80]#now i get all true value which is above 80

       Name  Math  Science  English  Computer  Social
3      Gita    94       33       55        99      83
15   Roshan    59       34       70        81      64
18   Aakash    61       98       63        84      81
19  Prakash    76       58       47        95      93
31   Binita   100       51       63        97      84
33    Rekha    77       86       96        87      45
38    Manoj    57       99       46        90      61

In [7]:
print(df[(df['Computer']>80) & (df['Social']>80)])

       Name  Math  Science  English  Computer  Social
3      Gita    94       33       55        99      83
18   Aakash    61       98       63        84      81
19  Prakash    76       58       47        95      93
31   Binita   100       51       63        97      84

In [17]:
df.where((df['Computer']>80) & (df['Social']>80),other='not eligible').head()#where doesnt change the row and column of a table

,Name,Math,Science,English,Computer,Social
0,not eligible,not eligible,not eligible,not eligible,not eligible,not eligible
1,not eligible,not eligible,not eligible,not eligible,not eligible,not eligible
2,not eligible,not eligible,not eligible,not eligible,not eligible,not eligible
3,Gita,94,33,55,99,83
4,not eligible,not eligible,not eligible,not eligible,not eligible,not eligible