In [16]:
import pandas as pd
import numpy as np

In [17]:
df=pd.read_csv('students.csv')
df.head()

    Name  Math  Science  English  Computer  Social
0    Ram    44       33       65        61      58
1   Sita    47       43       99        41      84
2   Hari    34       33       41        57      59
3   Gita    94       33       55        99      83
4  Shyam    58       87       65        30      50

In [18]:
df.loc[df.Name=='Ram','Math']=np.nan
df.head()

    Name  Math  Science  English  Computer  Social
0    Ram   NaN       33       65        61      58
1   Sita  47.0       43       99        41      84
2   Hari  34.0       33       41        57      59
3   Gita  94.0       33       55        99      83
4  Shyam  58.0       87       65        30      50

In [19]:
df.isna().sum()

Name        0
Math        1
Science     0
English     0
Computer    0
Social      0
dtype: int64

In [24]:
#fillup value in null
df['Math'] = df['Math'].fillna(df['Math'].mean())
df['Math'].head()

0    69.333333
1    47.000000
2    34.000000
3    94.000000
4    58.000000
Name: Math, dtype: float64