In [28]:
#import and export csv file

In [29]:
import pandas as pd

In [30]:
load_data=pd.read_csv('students.csv')

In [31]:
load_data.head()

    Name  Math  Science  English  Computer  Social
0    Ram    44       33       65        61      58
1   Sita    47       43       99        41      84
2   Hari    34       33       41        57      59
3   Gita    94       33       55        99      83
4  Shyam    58       87       65        30      50

In [32]:
load_data.tail()

      Name  Math  Science  English  Computer  Social
35  Asmita   100       59       58        30      39
36   Rohan    37       59       38        34      72
37   Priya    39       95       60        65      92
38   Manoj    57       99       46        90      61
39   Kusum    90       82       54        42      42

In [36]:
print(load_data[['Name','Math']].head())#it givest name and math columns details

    Name  Math
0    Ram    44
1   Sita    47
2   Hari    34
3   Gita    94
4  Shyam    58

In [37]:
print(load_data.loc[load_data.Name=='Ram'])#it gives the row  details

  Name  Math  Science  English  Computer  Social
0  Ram    44       33       65        61      58

In [38]:
print(load_data.iloc[0:2])#it is index  based location where it excluded the last index value

   Name  Math  Science  English  Computer  Social
0   Ram    44       33       65        61      58
1  Sita    47       43       99        41      84

In [40]:
print(load_data.loc[0:2])#it is structure lablel based location it included all value

   Name  Math  Science  English  Computer  Social
0   Ram    44       33       65        61      58
1  Sita    47       43       99        41      84
2  Hari    34       33       41        57      59